import type { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  return [
    {
      url: 'https://abofarha-paints.com/',
      lastModified,
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: 'https://abofarha-paints.com/aspagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-rakhis',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-shatir',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/muealim-sabagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/aisbgh-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-shatir-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/muealim-sabaagh-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/faniy-sabagh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-mumtaz-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/dikurat-sabagh-lilkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/manazil-sabaagh-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/shaqaq-sabaagh-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-buyut-aitfal',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-rusumat-aitfal',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-rakhisat-bi-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/dihanat-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/tarkib-waraq-judran',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/asbagh-abwab-khashabia',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/muealim-jabs-burd',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alsaalimia',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-sabah-alsaalim',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-hawalli',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-jaber-alahmad',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-khaitan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alfarwaniyah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-aljabriya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alshaab',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-bayan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-janoub-alsura',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-mubarak',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-mishref',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alzahraa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alsiddiq',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-hateen',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-salwa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alshuhadaa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-al-salam',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-al-masila',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-almasayel',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-abu-alhasania',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-subhan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-abu-ftaira',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-al-fintas',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-mubarak-al-kabeer',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alaqeela',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alfntas',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alraqa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-abu-halifa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alsabahiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-almanqaf',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-almahboula',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-al-ahmadi',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-al-khiran',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alfhahil',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alwafra',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-jaber-alali',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-fahad-alahmad',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-aldaiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-aldasma',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-aldohah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alkhaldiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alrawdah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alrai',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alshuwaykh',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-asharq',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alshamiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alsurra',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alqadesiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alqurawan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alfaihaa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-aladiliya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alsulaybikhat',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-kaifan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-qurtoba',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-ghranata',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-abdullah-al-salim',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-dasman',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-bneid-alqar',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alnahda',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alnuzha',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-almansouriya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-mantiqa-al-ashira',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alandalus',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alqrean',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alkswor',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-aladaan',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-saad-alabdullah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-aljahraa',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-abdullah-mubarak',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-gharb-abdullah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-janoub-abdullah',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alaardiya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alfardus',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-subah-alanasir',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagh-alromanisya',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/sabaagheen-alkuayt',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/muealim-tarkib-waraq-judran',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://abofarha-paints.com/muealim-tarkib-seramik',
      lastModified,
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  ];
}
